#!/bin/sh

# This hook prevents commiting changes when the css is not built for production

if [ $(wc -l < ui/assets/styles.css) -gt 1 ]; then
	echo "styles.css not minified: run 'npm run build' in ui/"
	exit 1
fi
